### ISSUE TITLE
Procedural Programming

### ISSUE THREAD

**Issue by msroji** [ZyadOsman/Programming-Challenges#4]
https://github.com/ZyadOsman/Programming-Challenges/blob/5dc74b1b325466104fc2a6edb4f61e2101515f95/Challenge%204/Wind_Chill.py#L1-L2

Write within a subroutine, and pass the user input as parameters to calculations()

This program is Incomplete. You also need to printout the first 3 lines as in the example output (for 10, 0 and -10 degrees)

**Comment by ZyadOsman** [comment]
ok will make a subroutine and output the first 3 lines
